### ISSUE TITLE
Default charts using Layercake

### ISSUE THREAD

**Issue by Wolfr** [Wolfr/sveltekit-jui#75]
I want https://layercake.graphics/ to be the default framework for charts in SvelteKit-Jui.

I want a copy-pastable example of common charts like a line chart and a bar chart.

But I first need to be able to implement it. Tracking this Github issue: https://github.com/mhkeller/layercake/issues/41

Currently stuck at:

```
10:37:15 PM [vite] Error when evaluating SSR module /node_modules/d3-format/src/formatSpecifier.js:
ReferenceError: formatSpecifier is not defined
    at /node_modules/d3-format/src/formatSpecifier.js:21:1
    at instantiateModule (/Users/johanronsse/Sites/sveltekit-jui/node_modules/vite/dist/node/chunks/dep-0776dd57.js:68919:166)
10:37:15 PM [vite] Error when evaluating SSR module /node_modules/d3-format/src/formatSpecifier.js:
ReferenceError: formatSpecifier is not defined
    at /node_modules/d3-format/src/formatSpecifier.js:21:1
    at instantiateModule (/Users/johanronsse/Sites/sveltekit-jui/node_modules/vite/dist/node/chunks/dep-0776dd57.js:68919:166) (x2)
10:37:15 PM [vite] Error when evaluating SSR module /node_modules/d3-time-format/src/defaultLocale.js:
ReferenceError: defaultLocale is not defined
    at /node_modules/d3-time-format/src/defaultLocale.js:9:1
    at instantiateModule (/Users/johanronsse/Sites/sveltekit-jui/node_modules/vite/dist/node/chunks/dep-0776dd57.js:68919:166)
10:37:15 PM [vite] Error when evaluating SSR module /node_modules/d3-color/src/color.js:
ReferenceError: color is not defined
```
Etc.

Branch: https://github.com/Wolfr/sveltekit-jui/tree/layercake

**Comment by Wolfr** [comment]
This was fixed in 0.3 - we also have examples of charts in the styleguide now.
